default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: projects
  password: <%= ENV['POSTGRES_PASSWORD'] %> 

development:
  <<: *default
  database: projects_development

test:
  <<: *default
  database: projects_test

production:
  <<: *default
  database: projects_production
  username: projects
  password: <%= ENV["PROJECTS_DATABASE_PASSWORD"] %> 